config/routes.rb
Demo::Application.routes.draw do
  get "say/goodnight"

  get "say/hello"

  get "say/goodbye"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/say_controller.rb
class SayController < ApplicationController
	def hello
		@time = Time.now
	end

	def goodbye
	end

  def goodnight

	  def say_goodnight(name)
	  	result = "Goodnight, #{name.capitalize}"
	  	return result
	  end 

	  def employees
	  	#employee_list = [ 'Yamen', 'Thomas', 'Don', 'Haritha' ]
	  	employee_list = %w{ Yamen Thomas Don Haritha }  # create an array
	  	employee_list.each { |employee| puts employee } # iterate over the contents of the array
	  end

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/say/goodbye.html.erb
<h1>Say#goodbye</h1>
<p>Find me in app/views/say/goodbye.html.erb</p>
<p>@time instance variable not defined in goodbye class in say controller.</p>

<p>Go to <a href="/say/hello">hello</a> page</p>
<p>Time to say <%= link_to_unless_current "hello", say_hello_path %></p>

app/views/say/goodnight.html.erb
<h1>Say#goodnight</h1>
<p>Find me in app/views/say/goodnight.html.erb</p>
<p>@time instance variable not defined in goodnight class in say controller.</p>

<p><%= say_goodnight('Yamen') %></p>

<p>Go to <a href="/say/hello">hello</a> page</p>
<p>Time to say <%= link_to "hello", say_hello_path %></p>

app/views/say/hello.html.erb
<h1>Say#hello</h1>
<p>Find me in app/views/say/hello.html.erb</p>
<p>It is now <%= @time %></p>

<p>Go to <a href="/say/goodbye">goodbye</a> page</p>
<p>Time to say <%= link_to "goodbye", say_goodbye_path %></p>